# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_92Aaht83H6Qz-mPN7gbI7qHU8cpk7nR
"""

rut_list = []
num_cal = [3, 2, 7, 6, 5, 4, 3, 2]
RPE = []
import operator
import math
g=2
v=2
def dv(n):
  x = sum(list(n))
  e = math.floor(x / 11)
  f = x - (11 * e)
  h = 11 - f

  if h == 11:
      h = "0"
  elif h == 10:
      h = "k"
  return str(h)
menucert= 9
Ver = 1
MP=1
Rut = ["21751534", "21584985"]
DV = ["3", "6"]
Nombre = ["Daniel Plasencia", "wilson valdivia"]
Edad = ["18", "20"]
PaisNac = ["Chile", "Peru"]
CiuNac = ["stgo", "lima"]
rut = input("ingrese su rut para validar si es apto a ingresar a el sistema (sin el DV)\n")
rut_list = []
for i in rut:
  rut_list.append(i)
  rut_list_int = [int(x) for x in rut_list]
  calculo = list(map(operator.mul, rut_list_int, num_cal))
Dvc = int(input("por favor ingrese el digito verificador de su rut\n"))

if str(Dvc) == dv(calculo):
 print("es apto,  Bienvenido al sistema")
 menuprincipal = int(input("menu principal: \n1-ver persona \n2-insertar persona \n3-elimina persona \n4-modificar persona\n5-Certificados\n0-salir \n"))

while menuprincipal != 0:
  if menuprincipal == 1:
      RutMi = int(input("Ingrese el RUT sin dígito verificador de la persona a mostrar:\n"))
      DVMi = input("Ingrese el DV de la persona a mostrar:\n")
      persona_encontrada = False
      for i in range(len(Rut)):
        if Rut[i] == str(RutMi) and DV[i] == DVMi:
          print("Rut (sin DV)\tDV\tNombre\tEdad\tPaís de nacimiento\tCiudad de nacimiento")
          print(Rut[i], "\t\t", DV[i], "\t\t", Nombre[i], "\t\t", Edad[i], "\t\t", PaisNac[i], "\t\t", CiuNac[i])
          persona_encontrada = True
          break
      if not persona_encontrada:
        print("Persona no encontrada")


  elif menuprincipal == 2:
    while Ver != 0:
      Ruk = input("Ingrese el Rut sin dígito verificador: ")
      DVI = input("Ingrese el dígito verificador: ")
      Ruk = Ruk.replace(".", "").replace("-", "")
      if not Ruk.isdigit() or len(Ruk) > 8 or len(DVI) > 1 or len(Ruk) < 8:
          print("El Rut ingresado no es válido")
          exit()
      rut = Ruk[::-1]
      factor = 2
      suma = 0
      for digito in rut:
        suma += int(digito) * factor
        factor += 1
        if factor == 8:
          factor = 2
      digito_esperado = 11 - (suma % 11)
      if digito_esperado == 11:
        digito_esperado = 0
      elif digito_esperado == 10:
        digito_esperado = "K"
      if str(digito_esperado) == DVI.upper():
        print("El Rut es válido")
        Rut.append(Ruk)
        DV.append(DVI)
        Ver = 0
      else:
        print("El Rut no es válido")
    Ver = 1
    while True:
      NP= input("ingrese el nombre de la persona\n")
      if len(NP)>7:
        Nombre.append(NP)
        break
      else:
        print("el nombre es invalido, debe tener minimo 8 caracteres\n")
    while True:
      EdadIng= int(input("ingrese la edad\n"))
      if EdadIng>0:
        Edad.append(EdadIng)
        break
      else:
        print("EDAD INVALIDA")
    PaisNac.append(input("ingrese pais de nacimiento de la persona\n"))
    CiuNac.append(input("ingrese ciudad de nacimiento de la persona\n"))
  elif menuprincipal == 3:
    RunE = int(input("Ingrese el rut de la persona a eliminar (sin DV):\n"))
    persona_encontrada = False
    for a in range(len(Rut)-1, -1, -1):
      if Rut[a] == str(RunE):
        del Rut[a]
        del DV[a]
        del Nombre[a]
        del Edad[a]
        del PaisNac[a]
        del CiuNac[a]
        persona_encontrada = True
        print("Persona eliminada")
  if not persona_encontrada:
    print("Persona no encontrada")
  elif menuprincipal == 4:
    print("MODIFICANDO PERSONA")
    run = int(input("ingrese codigo de la persona a modificar\n"))
    for l in range(len(Rut)-1, -1, -1):
      if Rut[l] == run:
        Nombre[l] = input("nuevo nombre \n")
        Edad[l] = int(input("nueva edad \n"))
        PaisNac[l] = input("nuevo pais de nacimiento\n")
        CiuNac[l] = input("nueva ciudad de nacimiento\n")
        print("persona modificada")
      else:
        print("persona no encontrada")
  elif menuprincipal == 5:
    while menucert != 0:
      menucert=int(input("ingrese la opcion de certificado que desea\n1-Certificado de Nacimiento\n2-Estado conyugal\n3-Residencia chilena\n0-volver al menu principal\n"))
      if menucert==1:
        NC= input("ingrese el nombre del titular para certificado: ")
        EC= int(input("ingrese la edad para certificado: "))
        ET=2023-EC
        RC= input("ingrese rut para certificado, sin puntos y con guion: ")
        SC=input("ingrese el sexo del titular del certificado(masculino o femenino): ")
        print("---------------------------------------------------------")
        print("           CERTIFICADO DE NACIMIENTO                      \n")
        print("lugar de nacimiento: CHILE")
        print("Nombre inscrito: ", NC)
        print("Año de nacimiento: ", ET)
        print("Rut inscrito: ", RC)
        print("Sexo inscrito: ", SC)
        print("----------------------------------------------------------")
      elif menucert==2:
        MAC=input("ingrese el nombre del marido: ")
        MUC=input("ingrese el nombre de la mujer: ")
        RMA=input("rut del marido: ")
        RMU=input("rut de la mujer: ")
        FC= input("ingrese fecha: ")
        print("-----------------------------------------------------------")
        print("               CERTIFICADO CONYUGAL")
        print("los suscritos, Don ", MAC," y Doña ", MUC, "con RUT ", RMA, " y ")
        print(RMU, "escritos correspondientemente les consta que su estado")
        print("civil es: CASADOS con fecha ", FC)
        print("Formulan la presente declaracion para ser usada en cualquier")
        print("entidad o para el fin que desee legalmente")
        print("Firma Testigo 1: ")
        print("Firma Testigo 2: ")
        print("-------------------------------------------------------------")
      elif menucert==3:
        NCR= input("ingrese el nombre del titular del certificado: ")
        RCR= input("ingrese rut del titular del certificado: ")
        CCR= input("ingrese comuna de residencia: ")
        DRC= input("ingrese calle y numeracion de residencia: ")
        print("---------------------------------------------------------------------")
        print("                     CERTIFICADO DE RESIDENCIA                       ")
        print("Se Certifica a Don(Doña) ", NCR, " con Rut ", RCR, "tiene residencia")
        print("en: ", CCR, DRC, "se extiende el siguiente certificado a ")
        print("peticion de el(la) interesado(a) para ser presentado en cualquier ")
        print("institucion legal")
        print("(no valido en casas comerciales ni bancos)")
        print("--------------------------------------------------------------------")
  menuprincipal = int(input("Menu Principal: \n1-Ver Persona\n2-Insertar persona \n3-Elimina persona \n4-Modificar persona\n5-Certificados\n0-salir \n"))
if menuprincipal == 0:
  print("Hasta pronto usuario", rut, "-",Dvc)
else:
  print("No es apto para ingresar al sistema, ingrese un rut valido")